#define DEBUG

#include "ast.h"
#include "frontend.h"

// Headers generated by flex and bison.
#include "lexer.h"
#include "parser.h"

#include <stdio.h>
#include <glib.h>
#include <assert.h>
int yyparse(int *bitLength);

GList* decl_root;
GList* stmt_root;

void done_parsing(GList* decl, GList* stmt) {
      decl_root = decl;
      stmt_root = stmt;
}
	
int main(int argc, char** argv) {
	if (argc!=3){
		fprintf(stderr,"usage: a.out filename bitlength\n"); 
		exit(1);
	}
	//get bitLength
	int bitLength = atoi(argv[2]);

	yyin = fopen(argv[1], "r");
	
      if (yyparse(&bitLength)) {
            fprintf(stderr, "Error: failed to parse.\n");
            if (yyin != stdin) fclose(yyin);
            exit(EXIT_FAILURE);
      }
	  //id_print("SMax", 4);

      /* Build the global environment, do typechecking. */	  
	  //decls_print(ast_root);

	  // create_global_env();
	  // type_check_decls(ast_root, gEnv, NULL);
	  // decls_print(ast_root);
	  //env_print(gEnv);
	  
	  //manually add main fx
	  printf("void main()\n");
	  printf("begin\n");
	  decls_print(decl_root, bitLength);
	  stmts_print(stmt_root, bitLength);
	  printf("end\n");

	  decls_destroy(decl_root);
	  stmts_destroy(stmt_root);

      if (yyin != stdin) fclose(yyin);
      yylex_destroy();
      exit(EXIT_SUCCESS);
}

